### ISSUE TITLE
Configuration settings not saved.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/title#3]
Head to `/admin/config/content/title` -> enable a few settings (I personally enabled all the "Automatic field replacement" checkboxes in all three tabs) -> save -> "The configuration options have been saved."

title.settings.json:

``` json
{
    "_config_name": "title.settings",
    "title_Array": null,
    "title_": null,
    "title_node": null,
    "title_n": null,
    "title_taxonomy_term": null,
    "title_t": null,
    "title_comment": null,
    "title_c": null,
    "title_file": null,
    "title_f": null,
    "title_user": null,
    "title_u": null
}

```

**Comment by klonos** [comment]
...there were no options in the config UI for file or user. The only vtabs available were "Node", "Taxonomy term" and "Comment".

**Comment by serundeputy** [comment]
Thanks @klonos 

I've updated the config form so it will save the config.

**Comment by klonos** [comment]
Thanx @serundeputy 👍 ...it seems to be saving config properly now. A quick question though: what about the `title_Array`, `title_file` and `title_user` entries in the config? They seem to not have respective tabs in the UI (`/admin/config/content/title`) is it a feature not implemented yet? ...plus, I understand file and user, but what is the `title_Array` used to store?
